url_shortener/short_urls/forms.py
from ipaddress import ip_address
from urllib.parse import urlsplit

from flask_wtf import FlaskForm
from wtforms.fields import BooleanField, URLField
from wtforms.validators import InputRequired, Optional, URL, ValidationError

from url_shortener.form_filters import prepend_http, strip_value


class ShortURLForm(FlaskForm):
    target_url = URLField(
        'Target URL',
        filters=[strip_value, prepend_http],
        validators=[InputRequired(), URL()],
    )
    public = BooleanField(
        'Make short URL public',
        default=True,
        filters=[],
        validators=[Optional()],
    )

    def validate_target_url(self, field):
        url_parts = urlsplit(field.data)
        try:
            ip = ip_address(url_parts.netloc)
        except ValueError:
            pass
        else:
            if not ip.is_global:
                raise ValidationError('Invalid URL.')

url_shortener/short_urls/__init__.py
from flask import Blueprint

from .views import index, url_preview, url_redirect


blueprint = Blueprint('short_urls', __name__)

blueprint.add_url_rule('/', view_func=index, methods=('GET', 'POST'))
blueprint.add_url_rule('/<slug>+', view_func=url_preview, methods=('GET',))
blueprint.add_url_rule('/<slug>', view_func=url_redirect, methods=('GET',))

url_shortener/short_urls/views.py
from flask import redirect, render_template, url_for

from url_shortener.database import db
from url_shortener.database.models import ShortURL
from url_shortener.short_urls.forms import ShortURLForm
from url_shortener.short_urls.slugs import generate_slug


def index():
    form = ShortURLForm()
    if form.validate_on_submit():
        # Generate unique slug and store in database
        short_url = ShortURL()
        while True:
            slug = generate_slug(length=6)
            if db.session.query(ShortURL.id).filter_by(slug=slug).first() is None:
                form.populate_obj(short_url)
                short_url.slug = slug
                db.session.add(short_url)
                db.session.commit()
                break

        # Redirect to url preview view
        return redirect(url_for('short_urls.url_preview', slug=short_url.slug))

    # Render form with a list of latest short URLs
    latest_short_urls = db.session.query(
        ShortURL.slug, ShortURL.target_url, ShortURL.visit_count
    ).filter_by(public=True).order_by(ShortURL.created_at.desc()).limit(10).all()
    return render_template(
            'short_urls/index.html', form=form, latest_short_urls=latest_short_urls)


def url_preview(slug):
    short_url = db.session.query(ShortURL).filter_by(slug=slug).first_or_404()
    return render_template('short_urls/url_preview.html', short_url=short_url)


def url_redirect(slug):
    short_url = db.session.query(ShortURL).filter_by(slug=slug).first_or_404()

    # Increment visit count
    short_url.visit_count = ShortURL.visit_count + 1
    db.session.commit()

    # Redirect to target URL
    return redirect(short_url.target_url)

url_shortener/templates/short_urls/index.html
{% extends "base.html" %}


{% block page_contents %}
<form method="POST" action="{{ url_for('short_urls.index') }}" novalidate>
    {{ form.csrf_token }}

    <div class="my-4">
        <div class="input-group input-group-lg my-2">
            {{ form.target_url(class_="form-control" + (" is-invalid" if form.target_url.errors else ""), placeholder=form.target_url.label.text) }}
            <input class="btn btn-primary" type="submit" value="Shorten!">
        </div>

        {% if form.errors %}
        <div class="mx-3 my-2 small text-danger">
            {% if form.target_url.errors %}
                {% for error in form.target_url.errors %}<p class="my-1">{{ error }}</p>{% endfor %}
            {% elif form.csrf_token.errors %}
                <p>Something went wrong while creating your short URL. Please try again.</p>
            {% endif %}
        </div>
        {% endif %}

        <div class="form-check mx-3 my-2">
            {{ form.public(class="form-check-input") }}
            {{ form.public.label(class="form-check-label") }}
        </div>
    </div>
</form>

{% if latest_short_urls %}
<div class="mt-5">
    <h3 class="mx-2 text-black-50">Last 10 URLs</h3>
    <table class="table table-borderless table-hover text-black-50">
        {% for short_url in latest_short_urls %}
        <tr>
            <td><a href="{{ url_for('short_urls.url_preview', slug=short_url.slug) }}"><span class="text-black-50">{{ request.host }}</span><strong>/{{ short_url.slug }}</strong></a></td>
            <td>{{ short_url.target_url }}</td>
            <td class="text-nowrap">{{ short_url.visit_count }} visit{{ short_url.visit_count|pluralize }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}
{% endblock %}

url_shortener/templates/short_urls/url_preview.html
{% extends "base.html" %}


{% block page_title %}/{{ short_url.slug }} &mdash; {{ super() }}{% endblock %}


{% block page_contents %}
<p class="small"><a href="{{ url_for("short_urls.index") }}">&lt; Back</a></p>

<div class="row my-3">
    <div class="col-4 col-md-3 col-lg-2"><strong>Target URL:</strong></div>
    <div class="col">{{ short_url.target_url|urlize(target="_blank") }}</div>
</div>
<div class="row my-3">
    <div class="col-4 col-md-3 col-lg-2"><strong>Times visited:</strong></div>
    <div class="col">{{ short_url.visit_count }}</div>
</div>
<div class="row my-3">
    <div class="col-4 col-md-3 col-lg-2"><strong>Public:</strong></div>
    <div class="col">{{ 'Yes' if short_url.public else 'No' }}</div>
</div>
<div class="row my-3">
    <div class="col-4 col-md-3 col-lg-2"><strong>Created:</strong></div>
    <div class="col">{{ short_url.created_at }}</div>
</div>
{% endblock %}